FROM python:3.11 AS mkdocs-builder

RUN mkdir /app
WORKDIR /app

COPY requirements-docs-site.txt requirements.txt
RUN pip install -r requirements.txt
COPY . .

RUN mkdir /build
RUN mkdocs build --site-dir /build

FROM nginx
COPY --from=mkdocs-builder /build /usr/share/nginx/html/
COPY ./nginx.conf /etc/nginx/nginx.conf