site_name: CNC Framework Site
site_url: https://cncframework.com
repo_url: https://github.com/coherenceplatform/cnc
theme:
  name: material
  custom_dir: overrides
  logo: images/cnc_logo_white.svg
extra_css:
  - 'stylesheets/custom.css'