name: Package CNC

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
          python3 -m pip install --upgrade build twine toml

    - name: Set package version and create artifact
      run: |
        PACKAGE_VERSION=${GITHUB_REF#refs/tags/}
        echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
        sed -i "s/^version = .*/version = \"$PACKAGE_VERSION\"/" pyproject.toml

    - name: Check if version already exists on PyPI
      run: |
        PACKAGE_NAME=cocnc
        PACKAGE_VERSION=${{ env.PACKAGE_VERSION }}
        VERSION_EXISTS=$(curl -s https://pypi.org/pypi/${PACKAGE_NAME}/json | python3 -c "import sys, json; data = json.load(sys.stdin); print('${PACKAGE_VERSION}' in data['releases'])")
        echo "VERSION_EXISTS=$VERSION_EXISTS" >> $GITHUB_ENV

    - name: Build the package
      if: env.VERSION_EXISTS == 'False'
      run: |
        python3 -m build

    - name: Publish to PyPI
      if: env.VERSION_EXISTS == 'False'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        python3 -m twine upload dist/*

    - name: Wait for new CNC package to be available on PyPI
      run: |
        sudo apt-get update && sudo apt-get install -y jq
        PACKAGE_NAME=cocnc
        PACKAGE_VERSION=${{ env.PACKAGE_VERSION }}
        MAX_ATTEMPTS=10
        ATTEMPT=1

        while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
          echo "Checking PyPI for $PACKAGE_NAME version $PACKAGE_VERSION (Attempt $ATTEMPT of $MAX_ATTEMPTS)"
          if curl -s "https://pypi.org/pypi/$PACKAGE_NAME/json" | jq -e ".releases[\"$PACKAGE_VERSION\"]" > /dev/null; then
            echo "Package $PACKAGE_NAME version $PACKAGE_VERSION found on PyPI"
            break
          fi

          if [ $ATTEMPT -eq $MAX_ATTEMPTS ]; then
            echo "Package not found after $MAX_ATTEMPTS attempts. Failing the workflow."
            exit 1
          fi

          ATTEMPT=$((ATTEMPT + 1))
          echo "Package not found. Waiting for 30 seconds before next attempt..."
          sleep 30
        done

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      id: cache-docker-layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to Google Cloud Registry
      uses: docker/login-action@v1
      with:
        registry: us-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}

    - name: Build base image
      id: docker_build_base
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./cncbuilder/Dockerfile.base
        push: true
        tags: us-docker.pkg.dev/coherence-public/public/cnc_base:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

    - name: Build and push prod image
      id: docker_build_prod
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./cncbuilder/Dockerfile
        push: true
        tags: us-docker.pkg.dev/coherence-public/public/cnc:latest, us-docker.pkg.dev/coherence-public/public/cnc:${{ env.PACKAGE_VERSION }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
        build-args: CNC_VERSION=${{ env.PACKAGE_VERSION }}

    - name: Notify Slack on failure
      if: failure() && (steps.docker_build_base.outcome == 'failure' || steps.docker_build_prod.outcome == 'failure')
      uses: slackapi/slack-github-action@v1
      with:
        payload: |
          {
            "text": "Docker build failed for CNC version ${{ env.PACKAGE_VERSION }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Docker build failed for CNC*\nVersion: ${{ env.PACKAGE_VERSION }}\nBase image build: ${{ steps.docker_build_base.outcome }}\nProd image build: ${{ steps.docker_build_prod.outcome }}"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Repo:*\n${{ github.repository }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Workflow:*\n${{ github.workflow }}"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Commit:*\n${{ github.sha }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Branch:*\n${{ github.ref }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}