name: Build and Push Docker image

on:
  workflow_run:
    workflows: ["PyPI Release"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      id: cache-docker-layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to Google Cloud Registry
      uses: docker/login-action@v1
      with:
        registry: us-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}

    - name: Download version artifact
      uses: actions/download-artifact@v4
      with:
        name: version
       
    - name: Set package version from artifact
      run: |
        VERSION=$(cat version.txt)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build base image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./cncbuilder/Dockerfile.base
        push: true
        tags: us-docker.pkg.dev/coherence-public/public/cnc_base:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
        
    - name: Build and push prod image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./cncbuilder/Dockerfile
        push: true
        tags:
        - us-docker.pkg.dev/coherence-public/public/cnc:latest
        - us-docker.pkg.dev/coherence-public/public/cnc:${{ env.VERSION }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
        build-args: CNC_VERSION=${{ env.VERSION }}