name: Build and Push Docker image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Google Cloud Registry
      uses: docker/login-action@v1
      with:
        registry: us-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}

    - name: Build base image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./cncbuilder/Dockerfile.base
        push: false
        load: true
        tags: cnc_base:latest

    - name: Build and push prod image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./cncbuilder/Dockerfile
        push: true
        tags: us-docker.pkg.dev/coherence-public/public/cnc:latest
